### ISSUE TITLE
Re-build Prototype functionality in Acetate

### ISSUE THREAD

**Issue by SamReeve96** [SamReeve96/Acetate#5]
Bring over features from Acetate Prototype, 

- [ ] ~~Sync with user storage for annotations~~
- [ ] ~~Public webpage annotation via Firebase*~~

_This will be dealt with in separate issue, for now the priority will be to get extensions working with Chrome user sync storage._

- [x] User can create/edit and delete annotations #28 
- [x] Use the chrome sync storage #30
- [x] toggle the extension via the popup (Done as part of #30)
- [x] Icon indicates Extension status (Done as part of #30)
- [ ] ~~Highlighting Elements on the page*~~
- [x] User can add new annotations via right click

* This functionality needs to be improved with this version of Acetate, being less buggy (element highlighting couldn't do text in an element, only the whole element.) or more full-featured (Allow users to initialise their own storage solutions other than firebase, or even private firebase solutions)

**Comment by SamReeve96** [comment]
Would be good to look into spacing cards based on element height (requiring updating on window resize) and handling cards overlapping etc.

**Comment by SamReeve96** [comment]
> Would be good to look into spacing cards based on element height (requiring updating on window resize) and handling cards overlapping etc.

Ehh too big to take on here. Same for Highlighting annotated elements will spin to separate issues
